### ISSUE TITLE
QG X checks (Release 24.03)

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sd-factory#92]
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner: @ciprianherciu 
Dev SPOC: @adkumar1 
Helm Chart Version: 2.1.11
App Version: 2.1.9

Release Managemnet Reference Issue:   

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md` https://github.com/eclipse-tractusx/sd-factory/issues/97
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container https://github.com/eclipse-tractusx/sd-factory/issues/93
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references 
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information https://github.com/eclipse-tractusx/sd-factory/issues/95

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml https://github.com/eclipse-tractusx/sd-factory/issues/92#issuecomment-1963569591
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  https://github.com/eclipse-tractusx/sd-factory/issues/96
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content https://github.com/eclipse-tractusx/sd-factory/pull/105
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation https://github.com/eclipse-tractusx/sd-factory/issues/94
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

**Comment by MehranRoshandel** [comment]
Hi,
The Product Owner is @Herciu, ***@***.***>.

Dr. Ing. Mehran Roshandel

T-Systems International GmbH
PU Digital Solutions | Data Intelligence Hub
Senior Product Manager
Holzhauser Str. 4-8
D-13509 Berlin
Tel. +49 1718672876
Email ***@***.******@***.***>

Let‘s power higher performance
 [signature_791559559] <https://dih.telekom.com/en/>
You can find the obligatory information on: www.t-systems.com/compulsory-statement<http://www.t-systems.com/compulsory-statement>


From: Evelyn Gurschler ***@***.***>
Sent: Wednesday, February 21, 2024 2:51 PM
To: eclipse-tractusx/sd-factory ***@***.***>
Cc: Roshandel, Mehran ***@***.***>; Mention ***@***.***>
Subject: [eclipse-tractusx/sd-factory] QG X checks (Release 24.03) (Issue #92)

QG checks

Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

Please keep this issue open until QG is concluded!

Product Owner: @MehranRoshandel<https://github.com/MehranRoshandel>
Dev SPOC: @adkumar1<https://github.com/adkumar1>
Helm Chart Version: 2.1.11
App Version: 2.1.9

Release Managemnet Reference Issue:

Check of Tractus-X Release Guidelines

  *   Currently implemented automatic checks can be found under your product on our Release Guidelines Checks Board<https://eclipse-tractusx.github.io/sig-release/>
  *   This QG Check is depending on the mandatory information from our current Release Guidelines<https://eclipse-tractusx.github.io/docs/release>

TRG 1 Documentation

  *   [ ] TRG 1.01<https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1> appropriate README.md
  *   [ ] TRG 1.02<https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2> appropriate install instructions either INSTALL.md or in README.md
  *   [ ] TRG 1.03<https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3> appropriate CHANGELOG.md
  *   [ ] TRG 1.04<https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4> editable static files

TRG 2 Git

  *   [ ] TRG 2.01<https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1> default branch is named main
  *   [ ] TRG 2.03<https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3> repository structure
  *   [ ] TRG 2.04<https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4> leading product repository
  *   [ ] TRG 2.05<https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5> .tractusx metafile in a proper format

TRG 3 Kubernetes

  *   [ ] TRG 3.02<https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2> persistent volume and persistent volume claim is used when needed

TRG 4 Container

  *   [ ] TRG 4.01<https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01> semantic versioning<https://semver.org/> and tagging
  *   [ ] TRG 4.02<https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02> base image is agreed
  *   [ ] TRG 4.03<https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03> image has USER command and Non Root Container
  *   [ ] TRG 4.05<https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05> released image must be placed in DockerHub, remove GHCR references
  *   [ ] TRG 4.06<https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06> separate notice file for DockerHub has all necessary information

TRG 5 Helm

  *   [ ] TRG 5.01<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01> Helm chart requirements
  *   [ ] TRG 5.02<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02> Helm chart location in /charts directory and correct structure
  *   [ ] TRG 5.03<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03> proper version strategy
  *   [ ] TRG 5.04<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04> CPU / MEM resource requests and limits and are properly set
  *   [ ] TRG 5.06<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06> Application must be configurable through the Helm chart
  *   [ ] TRG 5.07<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07> Dependencies are present and properly configured in the Chart.yaml
  *   [ ] TRG 5.08<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08> Product has a single deployable helm chart that contains all components
  *   [ ] TRG 5.09<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09> Helm Test running properly
  *   [ ] TRG 5.10<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10> Products need to support 3 versions at a time
  *   [ ] TRG 5.11<https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11> Upgradeability

TRG 6 Released Helm Chart

  *   [ ] TRG 6.01<https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1> Released Helm Chart

TRG 7 Open Source Governance

  *   [ ] TRG 7.01<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01> Legal Documentation
  *   [ ] TRG 7.02<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02> License and copyright header
  *   [ ] TRG 7.03<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03> IP checks for project content
  *   [ ] TRG 7.04<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04> IP checks for 3rd party content
  *   [ ] TRG 7.05<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05> Legal information for distributions
  *   [ ] TRG 7.06<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06> Legal information for end user content
  *   [ ] TRG 7.07<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07> Legal notice for documentation
  *   [ ] TRG 7.08<https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08> Legal notice for KIT documentation

Hints
Information Sharing

**Comment by evegufy** [comment]
I created https://github.com/eclipse-tractusx/sd-factory/pull/105 for automated dependencies check.

**Comment by evegufy** [comment]
> Regarding [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07): could you please provide some insight into how the app manages its state? I don't see any database dependency in the [Chart.yaml](https://github.com/eclipse-tractusx/sd-factory/blob/v2.1.9/charts/sdfactory/Chart.yaml)

@adkumar1 @ciprianherciu could one of you, please answer that question?

**Comment by adkumar1** [comment]
there are no database dependency for this application

**Comment by adkumar1** [comment]
There is 1 more PR https://github.com/eclipse-tractusx/sd-factory/pull/106
Can you please merge that as well

**Comment by evegufy** [comment]
@adkumar1 ok new chart version has been released, what about the docker images?

**Comment by adkumar1** [comment]
As all the changes for this release are completed so you can create a new docker image with v2.1.10 & release with tag v2.1.10

**Comment by evegufy** [comment]
> As all the changes for this release are completed, so you can create a new docker image with tag v2.1.10 & release with tag v2.1.10

done, I also created a new release https://github.com/eclipse-tractusx/sd-factory/releases/tag/v2.1.10
